ARG PYTHON_VERSION="3.13-slim"


FROM ghcr.io/astral-sh/uv:python3.13-trixie-slim AS builder
WORKDIR /app 
COPY requirements.txt .
RUN uv venv /app/.venv && uv pip install --no-cache-dir -r requirements.txt

FROM python:$PYTHON_VERSION
WORKDIR /app
COPY --from=builder /app/.venv /app/.venv
ENV PATH="/app/.venv/bin:$PATH"
COPY api.py .

RUN groupadd -r appgroup && useradd -r -g appgroup glad
USER glad

EXPOSE 3000
CMD [ "uvicorn","api:app","--host","0.0.0.0","--port","3000" ]


HEALTHCHECK --interval=5m --timeout=3s \
  CMD uv --version && python3 -c "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')" || exit 1

